# Generated by Django 3.0.8 on 2020-07-31 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200730_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID')),
                ('stop', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='auctions.Listing')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Bid')),
            ],
        ),
    ]
